author: ShadowCasted K1ds
main: com.shadowcasted.shadowbans.ShadowBans
name: ShadowBans
version: 0.0.3
commands:
  ban:
    description:
  unban:
    description:
  tempban:
    description:
  checkban:
    description:
  uuid:
    description: